[package]
name = "cmp"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = ["est31 <MTest31@outlook.com>"]

[dependencies]
lewton = { path = "../../" }
vorbis = "0.0"
time = "0.1"
test-assets = "0.1"
